name: Dutch Art Daily
description: A new Dutch Golden Age artwork delivered every day!
url: http://www.dutchartdaily.com
markdown: kramdown
# highlighter: pygments
relative_permalinks: false
doctor: true
show_drafts: true

timezone:       America/New_York
source:         .
destination:    ./_site
plugins:        ./_plugins
layouts:        ./_layouts
include:        ['.htaccess']
permalink:      /post/:month-:day/

gems: [
  rubygems,
]

# Compress layout settings
compress_html:
  clippings: all
  comments: []
  endings: []
  ignore:
    envs: []
  blanklines: false
  profile: false
  startings: []


include: [
  # '_slides'
]

exclude: [
    'node_modules',
    'grunt',
    'source',
    'assets',
    'gulpfile.js',
    'config.rb',
    '*.log',
    '*.DS_Store',
    'Gemfile',
    'Gemfile.lock',
    '.sass-cache',
    'package.json',
    'js/src/*'
]
